name: npm-publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish to npm
      uses: pascalgn/npm-publish-action@1.2.0
